# Generated by Django 5.0.6 on 2024-07-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toc_toc', '0002_rename_cant_baños_inmueble_num_baños_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='precio_mensual',
            new_name='precio',
        ),
    ]
