# Generated by Django 5.0.6 on 2024-07-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toc_toc', '0003_rename_precio_mensual_inmueble_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario'), ('admin', 'Admin')], default='arrendatario', max_length=255),
        ),
    ]
