# Generated by Django 5.0.6 on 2024-07-27 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toc_toc', '0004_userprofile_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='Inmueble',
            new_name='inmueble',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inmuebles', to='toc_toc.comuna'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('bodega', 'Bodega'), ('parcela', 'Parcela')], max_length=255),
        ),
    ]
